/**
 * Created by jahansj on 20/10/2016.
 */

export const _CLICK_BUTTON = 'CLICK_BUTTON';
export const _UPDATE_SALARY = 'UPDATE_SALARY';
export const _UPDATE_HOURS_PER_WEEK = 'UPDATE_HOURS_PER_WEEK';
export const _UPDATE_AMOUNT_OF_BREAKS = 'UPDATE_AMOUNT_OF_BREAKS';
export const _UPDATE_AVERAGE_LENGTH_OF_BREAKS = 'UPDATE_AVERAGE_LENGTH_OF_BREAKS';