/**
 * Created by jahansj on 20/10/2016.
 */

/**
 * Update user data
 * @type {string}
 */
export const _UPDATE_ERROR = 'UPDATE_ERROR';
export const _UPDATE_SALARY = 'UPDATE_SALARY';
export const _UPDATE_HOURS_PER_WEEK = 'UPDATE_HOURS_PER_WEEK';
export const _UPDATE_AMOUNT_OF_BREAKS = 'UPDATE_AMOUNT_OF_BREAKS';
export const _UPDATE_AVERAGE_LENGTH_OF_BREAKS = 'UPDATE_AVERAGE_LENGTH_OF_BREAKS';
export const _UPDATE_TOILET_TIME_PER_YEAR = 'UPDATE_TOILET_TIME_PER_YEAR';
export const _UPDATE_TOILET_TIME_PER_MONTH = 'UPDATE_TOILET_TIME_PER_MONTH';
export const _UPDATE_TOILET_TIME_PER_WEEK = 'UPDATE_TOILET_TIME_PER_WEEK';
export const _UPDATE_TOILET_PAY_PER_YEAR = 'UPDATE_TOILET_PAY_PER_YEAR';
export const _UPDATE_TOILET_PAY_PER_MONTH = 'UPDATE_TOILET_PAY_PER_MONTH';
export const _UPDATE_TOILET_PAY_PER_WEEK = 'UPDATE_TOILET_PAY_PER_WEEK';

/**
 * Login process
 * @type {string}
 */
export const _LOGIN_CREDENTIALS_REQUEST = 'LOGIN_CREDENTIALS_REQUEST';
export const _LOGIN_CREDENTIALS_FAILURE = 'LOGIN_CREDENTIALS_FAILURE';
export const _LOGIN_CREDENTIALS_SUCCESS = 'LOGIN_CREDENTIALS_SUCCESS';